### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by RitaChang5527**
老師您好 我是張紫綾 想請您幫忙看作業
[台北一日遊](http://3.106.33.239:3000)

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Add some spacing between attraction box in middle size of devices.
2. There should have 2 pages if we search 北

**Comment by RitaChang5527** [comment]
老師 想麻煩您 幫我看作業！

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. You can use innerHTML to clear content of an element, but don't use it to append content in an element. Because it will rerender all the existing child elements, for example, every time you load next new data, your page will load all the attraction boxes again.
2. MRT list layout is broken in small to middle size of devices.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Scrolling effect of MRT list does not meet the baseline of requirement. You can refer to some examples, https://www.airbnb.com/ or what I have done in our meet recordings.

**Review by cwpeng — CHANGES_REQUESTED** [review]
I do not see any changes.

**Comment by RitaChang5527** [comment]
老師 不好意思，誤會您的意思，想再麻煩您幫我看一次，謝謝您

**Review by cwpeng — CHANGES_REQUESTED** [review]
Cannot connect to your website.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
