### PR TITLE
booking

### PR DESCRIPTION
**Pull request by RitaChang5527**
老師~ 我是紫綾 想麻煩您幫我看作業！
[台北一日遊](http://3.106.33.239:3000/)

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. We should redirect user to homepage when user visits booking page without singing in.
2. I cannot add booking if there exists booking data.
3. Your server is down after some testings.

**Comment by RitaChang5527** [comment]
老師~想麻煩您再幫我看一次作業 謝謝您

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. We should redirect user to homepage when user visits booking page without singing in.
2. Your page send many repeated API calls to backend in booking page.

Screenshot 2023-10-01 164835

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your code in frontend send many repeated API calls to backend in many pages.

It means you cannot handle your JavaScript code properly, so you have to fix them all. Try to investigate your webpage in network tab of developer console, just like what I screenshoted.

**Comment by RitaChang5527** [comment]
老師 很抱歉多花您時間 想再麻煩您幫我看作業 謝謝您

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your server is down when I try to visit /booking without signing in.

**Comment by RitaChang5527** [comment]
老師 不好意思 可以再麻煩您幫我試試看嗎

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
