### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by RitaChang5527**
Discord : ritachang 張紫綾
老師~~想麻煩您幫我看作業

[page0](http://3.104.189.22:3000/api/attractions?page=0)

[南港山系-象山親山步道](http://3.104.189.22:3000/api/attraction/10)

[mrts](http://3.104.189.22:3000/api/mrts)

### CODE REVIEW

**Comment by cwpeng** [comment]
Your server is down for now.

**Comment by RitaChang5527** [comment]
老師 我把server開起來了，想再麻煩您幫我看

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Field names of response should align with API document. For example, `image_url` should be `images`.
2. Response of http://3.104.189.22:3000/api/attractions?page=0 contains many duplicated attraction data.
3. `images` field of attraction should be a string array where every image URL of attraction should be a element in this array. For example: `["Image URL 1", "Image URL 2", ...]`

Fix issues and re-request review.

**Comment by RitaChang5527** [comment]
老師~ 可以請您在幫我看一次嗎！謝謝您

[page0](http://3.104.189.22:3000/api/attractions?page=0)

[南港山系-象山親山步道](http://3.104.189.22:3000/api/attraction/10)

[mrts](http://3.104.189.22:3000/api/mrts)

**Comment by cwpeng** [comment]
Re-request review from top right corner in this pull request so that I can review for you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Field names of attraction data is incorrect. You should review every related part of an issue.
2. http://3.104.189.22:3000/api/attraction/10 should contain multiple image URLs in `images` field.
3. http://3.104.189.22:3000/api/attractions?page=0&keyword=%E5%8A%8D%E6%BD%AD should contain some attraction data.

Fix issues and re-request review.

**Comment by RitaChang5527** [comment]
老師 真的不好意思 想請您再看一次 謝謝您

**Comment by RitaChang5527** [comment]
老師 不好意思 麻煩您這麼多次 我終於搞懂了

[page0](http://3.106.33.239:3000/api/attractions?page=0)

[keyword劍潭](http://3.106.33.239:3000/api/attractions?page=0&keyword=劍潭)

[ id=10 南港山系-象山親山步道](http://3.106.33.239:3000/api/attraction/10)

[mrts](http://3.106.33.239:3000/api/mrts)

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done, but response of `/api/attractions` should have a `nextPage` field.

**Comment by RitaChang5527** [comment]
老師 已修正！

[page0](http://3.106.33.239:3000/api/attractions?page=0)

**Comment by RitaChang5527** [comment]
老師 我有重按Re-request 了

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
