### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by RitaChang5527**
老師~您好 想請您幫忙看作業
[台北一日遊](http://3.106.33.239:3000)

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Separating lines should only 1px height with light grey color.
2. There is no space between navigator bar and image slider in mobile layout.
3. Your layout exceeds screen width in many small size devices.

**Comment by RitaChang5527** [comment]
老師 很抱歉 我沒有注意到我更動到html，想再麻煩您幫我看一次

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Your separating line is still 2px height.
2. There is no space between navigator bar and image slider in mobile layout.

3 106 33 239_3000_attraction_2

**Comment by RitaChang5527** [comment]
老師~想麻煩您幫我看作業 謝謝您

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your server is down.

**Review by cwpeng — APPROVED** [review]
OK. Done.

But you have to learn how to use git from command line, don't upload file from webpage in the next time, I will reject it. It's basic ability to be a software enginner, even if front-end engineer.

**Pull request merged**
